// Generated by ReScript, PLEASE EDIT WITH CARE


function make(ea) {
  return {
          TAG: "Reader",
          _0: ea
        };
}

function run(r, env) {
  return r._0(env);
}

function ask() {
  return {
          TAG: "Reader",
          _0: (function (env) {
              return env;
            })
        };
}

function asks(ea) {
  return {
          TAG: "Reader",
          _0: (function (env) {
              return ea(env);
            })
        };
}

function local(r, fe) {
  return {
          TAG: "Reader",
          _0: (function (env) {
              return run(r, fe(env));
            })
        };
}

function map(r, fab) {
  return {
          TAG: "Reader",
          _0: (function (env) {
              return fab(run(r, env));
            })
        };
}

function chain(ea, fab) {
  var ea$1 = ea._0;
  return {
          TAG: "Reader",
          _0: (function (env) {
              return run(fab(ea$1(env)), env);
            })
        };
}

function chainFirst(ea, fab) {
  var ea$1 = ea._0;
  return {
          TAG: "Reader",
          _0: (function (env) {
              run(fab(ea$1(env)), env);
              return ea$1(env);
            })
        };
}

export {
  make ,
  run ,
  ask ,
  asks ,
  local ,
  map ,
  chain ,
  chainFirst ,
}
/* No side effect */
