// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Helpers from "./Helpers.mjs";

function $$return(f) {
  return {
          TAG: "State",
          _0: f
        };
}

function make(a) {
  return {
          TAG: "State",
          _0: (function (s) {
              return [
                      a,
                      s
                    ];
            })
        };
}

function run(f, init) {
  return f._0(init);
}

function chain(st, fab) {
  return {
          TAG: "State",
          _0: (function (state) {
              var match = run(st, state);
              var stb = fab(match[0]);
              return stb._0(match[1]);
            })
        };
}

function chainFirst(st, fab) {
  return {
          TAG: "State",
          _0: (function (s) {
              var match = run(st, s);
              return run(fab(match[0]), match[1]);
            })
        };
}

function map(sm, fab) {
  return chain(sm, (function (a) {
                var a$1 = fab(a);
                return {
                        TAG: "State",
                        _0: (function (s) {
                            return [
                                    a$1,
                                    s
                                  ];
                          })
                      };
              }));
}

function get() {
  return {
          TAG: "State",
          _0: (function (s) {
              return [
                      s,
                      s
                    ];
            })
        };
}

function put(s) {
  return {
          TAG: "State",
          _0: (function (param) {
              return [
                      undefined,
                      s
                    ];
            })
        };
}

function modify(f) {
  return {
          TAG: "State",
          _0: (function (s) {
              return [
                      undefined,
                      f(s)
                    ];
            })
        };
}

function gets(f) {
  return {
          TAG: "State",
          _0: (function (s) {
              return [
                      f(s),
                      s
                    ];
            })
        };
}

function ap(fa, fab) {
  return {
          TAG: "State",
          _0: (function (s) {
              var match = run(fa, s);
              var match$1 = run(fab, match[1]);
              return [
                      match$1[0](match[0]),
                      match$1[1]
                    ];
            })
        };
}

function flatten(mma) {
  return chain(mma, Helpers.identity);
}

export {
  $$return ,
  make ,
  run ,
  chain ,
  chainFirst ,
  map ,
  get ,
  put ,
  modify ,
  gets ,
  ap ,
  flatten ,
}
/* Helpers Not a pure module */
